export const SET_TITLE = 'SET_TITLE'

export const SET_USER = 'SET_USER'

export const SET_USER_NAME = 'SET_USER_NAME'

export const REMOVE_USER = 'REMOVE_USER'

export const SET_ROOMS = 'SET_ROOMS'

export const SET_CHANGED_ROOM = 'SET_CHANGED_ROOM'

export const SET_CURRENT_ROOM = 'SET_CURRENT_ROOM'

export const SET_CURRENT_ROOM_STATE = 'SET_CURRENT_ROOM_STATE'

export const SET_CURRENT_ROOM_CHESSES = 'SET_CURRENT_ROOM_CHESSES'